### ISSUE TITLE
[Bug] JSON errors returned while chatting

### ISSUE THREAD

**Issue by marcusschiesser** [marcusschiesser/unc#4]
**Describe the bug**
While chatting, the user gets JSON parse error messages from the AI like:
```
{
  "error": true,
  "message": "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"
}
```
or
```
{
  "error": true,
  "message": "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"
}
```
In the current production, the console log shows the following error:
```
[Request] failed to make a chat request SyntaxError: Unexpected end of JSON input
    at s.chat (4682-b78a07a9c7dfe114.js:1:2349)
    at async d (2752.0c43510d3176525d.js:1:4135)
    at async p (2752.0c43510d3176525d.js:1:3934)
```

**To Reproduce**
We don't have a clear test case, I guess it depends on the data the LLM returns. A user reported it while using the telegram bot feature, but my hunch is this is unrelated.

**Expected behavior**
Don't show an error.

**Comment by marcusschiesser** [comment]
@LaDoger said the bug happens with a long replies in Telegram but I cannot reproduce it. Tested with:
![image](https://github.com/marcusschiesser/ur-neural-consultants/assets/51660321/aa1e230e-c7e0-409e-ba8d-cc211dcedf85)

**Comment by LaDoger** [comment]
This bug occurs from time to time. I don't know how to reproduce it yet. We will keep trying.
